name: Deploy to test

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Frontend
        run: |
          npm ci
          npm run build
        cache:
          paths:
            - 'frontend/node_modules'
            - 'frontend/package-lock.json'

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          source: "./build"
          target: /home/deploy/observer

      - name: Check and Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            if sudo systemctl is-active nginx; then
              echo "Nginx is already running, no action needed."
            else
              sudo systemctl restart nginx
              echo "Restarted Nginx."
            fi
